"""add pilot feedback table

Revision ID: dcce51c3ee5a
Revises: a3297a7e37e9
Create Date: 2026-08-26 18:07:04.369147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcce51c3ee5a'
down_revision = 'a3297a7e37e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilot_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('challenge', sa.Text(), nullable=False),
    sa.Column('ai_feedback_helpful', sa.String(length=50), nullable=False),
    sa.Column('most_valuable_feedback', sa.Text(), nullable=False),
    sa.Column('confusing_inaccurate_unnecessary', sa.Text(), nullable=True),
    sa.Column('would_use_again', sa.String(length=50), nullable=False),
    sa.Column('desired_improvement', sa.Text(), nullable=True),
    sa.Column('pro_interest', sa.String(length=50), nullable=False),
    sa.Column('pro_price_interest', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('scores_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'interview_sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('scores_session_id_fkey'), 'interview_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    op.drop_table('pilot_feedback')
    # ### end Alembic commands ###
